TASK #1: IMPORT LIBRARIES AND DATASETS

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
british_airways_df = pd.read_csv('../data/British_Airways_Data.csv')

Task #2:EXPLORE DATASET

In [8]:
british_airways_df.head()

,Name,Date,Location,Short Summary,Verification,Full Review,Rating,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Inflight Entertainment,Ground Service,Wifi & Connectivity,Value For Money,Recommended
0,Robert Bone,3rd April 2025,United Kingdom,"""one of the best BA First flights I’ve had""",Not Verified,LHR T5 BA Gold Wing worked well. Pleasant chec...,9.0,Boeing 777 200,Business,First Class,London to Seattle,April 2025,5.0,5.0,5.0,5.0,4.0,3.0,4,yes
1,J Jones,31st March 2025,United Kingdom,"""Very good service on this route""",Not Verified,Very good service on this route BA2710 30th Ma...,10.0,A320,Couple Leisure,Business Class,London Gatwick to Fuerteventura,March 2025,4.0,5.0,5.0,NaN,4.0,NaN,4,yes
2,J Meares,19th March 2025,United Kingdom,"""disagreeable flight attendant""",✅ Trip Verified,Flight mainly let down by a disagreeable fligh...,7.0,Boeing 787,Solo Leisure,Business Class,Cape Town to London,March 2025,5.0,2.0,5.0,5.0,4.0,1.0,4,yes
3,Luis De Jesus,16th March 2025,United States,"""flight was delayed nearly 1 hour""",✅ Trip Verified,Another awful experience by British Airways. T...,1.0,NaN,Business,Business Class,London to Geneva,December 2024,1.0,1.0,NaN,NaN,1.0,NaN,1,no
4,Luis De Jesus,16th March 2025,United States,"""full of attitude to me""",✅ Trip Verified,"The service was rude, full of attitude to me, ...",3.0,NaN,Business,Premium Economy,London to New York,January 2025,1.0,1.0,1.0,NaN,5.0,NaN,1,no

In [9]:
british_airways_df.tail()

,Name,Date,Location,Short Summary,Verification,Full Review,Rating,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Inflight Entertainment,Ground Service,Wifi & Connectivity,Value For Money,Recommended
3921,Bruce Bettridge,29th August 2012,United Kingdom,British Airways customer review,Not Verified,Business LHR to BKK. 747-400. First try back w...,4.0,NaN,NaN,Business Class,NaN,NaN,4.0,3.0,2.0,3.0,NaN,NaN,2,no
3922,Nick Berry,28th August 2012,United Kingdom,British Airways customer review,Not Verified,LHR to HAM. Purser addresses all club passenge...,9.0,NaN,NaN,Business Class,NaN,NaN,4.0,5.0,4.0,0.0,NaN,NaN,3,yes
3923,Avril Barclay,12th October 2011,United Kingdom,British Airways customer review,Not Verified,My son who had worked for British Airways urge...,5.0,NaN,NaN,Economy Class,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,yes
3924,C Volz,11th October 2011,United States,British Airways customer review,Not Verified,London City-New York JFK via Shannon on A318 b...,4.0,NaN,NaN,Premium Economy,NaN,NaN,1.0,3.0,5.0,0.0,NaN,NaN,1,no
3925,Russ King,9th October 2011,United Kingdom,British Airways customer review,Not Verified,SIN-LHR BA12 B747-436 First Class. Old aircraf...,4.0,NaN,NaN,First Class,NaN,NaN,4.0,5.0,5.0,2.0,NaN,NaN,2,no

In [10]:
british_airways_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3926 entries, 0 to 3925
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    3926 non-null   object
 1   Date                    3926 non-null   object
 2   Location                3924 non-null   object
 3   Short Summary           3926 non-null   object
 4   Verification            3926 non-null   object
 5   Full Review             3926 non-null   object
 6   Rating                  3922 non-null   float64
 7   Aircraft                2046 non-null   object
 8   Type Of Traveller       3155 non-null   object
 9   Seat Type               3924 non-null   object
 10  Route                   3150 non-null   object
 11  Date Flown              3148 non-null   object
 12  Seat Comfort            3799 non-null   float64
 13  Cabin Staff Service     3784 non-null   float64
 14  Food & Beverages        3487 non-null   float64
 15  Inflight Entertainment  2681 non-null   float64
 16  Ground Service          3076 non-null   float64
 17  Wifi & Connectivity     689 non-null    float64
 18  Value For Money         3926 non-null   int64
 19  Recommended             3926 non-null   object
dtypes: float64(7), int64(1), object(12)
memory usage: 613.6+ KB

In [11]:
british_airways_df.describe()

,Rating,Seat Comfort,Cabin Staff Service,Food & Beverages,Inflight Entertainment,Ground Service,Wifi & Connectivity,Value For Money
count,3922.000000,3799.000000,3784.000000,3487.000000,2681.000000,3076.000000,689.000000,3926.000000
mean,4.676951,2.858121,3.232558,2.708919,2.647893,2.755852,1.940493,2.661233
std,3.176669,1.366349,1.492367,1.440695,1.407550,1.464112,1.339559,1.470685
min,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,4.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000,3.000000
75%,8.000000,4.000000,5.000000,4.000000,4.000000,4.000000,3.000000,4.000000
max,10.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000